#:kivy 1.0.9

#name: 'p', [False, True, False, False]
#line: 0, {0: [1], 1: [0]}

RootWidget:
    pos: [0, 0]
    size: [876.35, 669.0]
    NexusWidget:
        pos: [489.0, 331.0]
        size: [12, 12]
        color: .800, .800, .800
        line_info: [(0, 1)]
    AtomWidget:
        pos: [256.0, 328.0]
        size: [11, 20]
        color: .800, .800, .800
        text: 'p'
        line_info: [(0, 0)]