#:kivy 1.0.9

#name: 'q', [True, False, False, False]
#name: 'p', [False, True, False, False]
#line: 0, {0: [1], 1: [0]}

RootWidget:
    pos: [0, 0]
    size: [876.35, 669.0]
    AtomWidget:
        pos: [572.0, 327.99999999999994]
        size: [11, 20]
        color: .800, .800, .800
        text: 'q'
        line_info: [(0, 1)]
    AtomWidget:
        pos: [256.0, 328.0]
        size: [11, 20]
        color: .800, .800, .800
        text: 'p'
        line_info: [(0, 0)]