#:kivy 1.0.9

#name: 'q', [True, False, False, False]
#name: 'p', [False, True, False, False]
#name: 'r', [True, False, False, False]
#line: 0, {0: [1], 1: [0, 2, 3], 2: [1], 3: [1]}
#line: 1, {0: [1], 1: [0, 2, 3], 2: [1], 3: [1]}

RootWidget:
    pos: [0, 0]
    size: [876.35, 669.0]
    NexusWidget:
        pos: [339.0, 523.0]
        size: [12, 12]
        color: .800, .800, .800
        line_info: [(0, 1)]
    EllipseWidget:
        pos: [365.0, 120.00000000000003]
        size: [283.0, 200.00000000000006]
        color: .800, .800, .800
        NexusWidget:
            pos: [445.0, 218.0]
            size: [12, 12]
            line_info: [(1, 1)]
        AtomWidget:
            pos: [532.0, 165.0]
            size: [7, 20]
            text: 'r'
            line_info: [(1, 3)]
        AtomWidget:
            pos: [536.0, 269.0]
            size: [11, 20]
            text: 'q'
            line_info: [(1, 2)]
    EllipseWidget:
        pos: [389.0, 437.0]
        size: [262.0, 184.0]
        color: .800, .800, .800
        AtomWidget:
            pos: [526.0, 478.99999999999994]
            size: [7, 20]
            text: 'r'
            line_info: [(0, 3)]
        AtomWidget:
            pos: [539.0, 566.0]
            size: [11, 20]
            text: 'q'
            line_info: [(0, 2)]
    AtomWidget:
        pos: [170.0, 201.00000000000003]
        size: [11, 20]
        color: .800, .800, .800
        text: 'p'
        line_info: [(1, 0)]
    AtomWidget:
        pos: [161.0, 522.0]
        size: [11, 20]
        color: .800, .800, .800
        text: 'p'
        line_info: [(0, 0)]