#:kivy 1.0.9

#name: 'a', [False, False, False, False]
#name: 'b', [False, False, False, False]
#name: 'c', [False, False, False, False]
#name: 'd', [False, False, False, False]
#name: 'e', [False, False, False, False]
#name: 'f', [False, False, False, False]

RootWidget:
    pos: [0, 0]
    size: [1920, 1061]
    AtomWidget:
        pos: [769.0, 892.0]
        color: .800, .800, .800
        text: 'a'
    AtomWidget:
        pos: [1010.0, 891.0]
        color: .800, .800, .800
        text: 'b'
    EllipseWidget:
        pos: [606.0, 326.0]
        color: .800, .800, .800
        size: [629.0, 501.0000000000001]
        AtomWidget:
            pos: [749.0, 695.0]
            text: 'c'
        SquareWidget:
            pos: [728.0, 452.0]
            size: [411.0, 141.0]
            AtomWidget:
                pos: [791.0, 513.0]
                color: .800, .800, .800
                text: 'd'
            AtomWidget:
                pos: [972.0, 506.0]
                color: .800, .800, .800
                text: 'e'
        SquareWidget:
            pos: [974.0, 626.0]
            size: [140.0, 113.0]
            AtomWidget:
                pos: [1011.0, 670.0]
                color: .800, .800, .800
                text: 'f'
